SET PATH_TO_RESULTS_DIR=C:\mdp-test\TESTS\SMZU\!res
SET DNAME_ETALON=res_24_06_2024__09_40_39.737_new_ref
SET DNAME_NEW=res_24_06_2024__10_18_25.201

SET PATH_FILE_ETALON_JSON="%PATH_TO_RESULTS_DIR%\%DNAME_ETALON%\_calc_.json"
SET PATH_FILE_NEW_JSON="%PATH_TO_RESULTS_DIR%\%DNAME_NEW%\_calc_.json"
SET PATH_FILE_CMP_TXT="%PATH_TO_RESULTS_DIR%\%DNAME_NEW%\_cmp_.txt"
"C:\Program Files (x86)\Python312-32\python.exe" C:\mdp-test\TESTS\SMZU\scrpts\tst_cmp.py %PATH_FILE_ETALON_JSON% %PATH_FILE_NEW_JSON%
start notepad++.exe  %PATH_FILE_CMP_TXT%

SET PATH_FILE_ETALON_HTML="%PATH_TO_RESULTS_DIR%\%DNAME_ETALON%\_calc_.html"
SET PATH_FILE_NEW_HTML="%PATH_TO_RESULTS_DIR%\%DNAME_NEW%\_calc_.html"
start C:\Windiff\WinDiff.exe %PATH_FILE_ETALON_HTML%  %PATH_FILE_NEW_HTML%

